#!/bin/sh
set -eu

repository=$(git rev-parse --show-toplevel)
git_local_environment=$(git rev-parse --local-env-vars)
unset $git_local_environment
cd "$repository"

printf '%s\n' "machstrap hook: running fast checks before push" >&2
./tests/run-tests.sh
